name: rag-agent
services:
  - name: api
    github:
      branch: main
      deploy_on_push: true
    build_command: pip install -r requirements.txt
    run_command: cd rag_agent && uvicorn fastapi_app:app --host 0.0.0.0 --port 8080
    envs:
      - key: GOOGLE_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: RAG_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: ENVIRONMENT
        scope: RUN_TIME
        value: production
      - key: ENABLE_DOCS
        scope: RUN_TIME
        value: "true"
      - key: LOG_LEVEL
        scope: RUN_TIME
        value: INFO
    instance_size_slug: basic-xxs
    instance_count: 1
    http_port: 8080
    source_dir: /
